name: sable
description: The Ultra-Human AI Assistant.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  http: ^1.1.2
  intl: ^0.19.0
  uuid: ^4.2.2
  path_provider: ^2.1.1
  flutter_animate: ^4.5.2
  google_fonts: ^6.1.0
  lucide_icons: ^0.257.0
  go_router: ^13.0.0
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env

